[project]
name = "redirect-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular[sidecar]>=0.30.0",
    "gunicorn>=26.1.0",
    "psycopg[binary]>=3.3.4",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.4",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
pythonpath = ["src"]
python_files = ["test_*.py"]
testpaths = ["src"]

[tool.ruff]
line-length = 99
target-version = "py312"
extend-exclude = ["**/migrations/*"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
